# SPDX-FileCopyrightText: 2006-2025 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2025 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: Workflows

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - unlabeled
  workflow_dispatch:

concurrency:
  group: workflows-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  SHARG_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'lint'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Nextflow"
            compiler: "gcc-latest"
          - name: "CWL"
            compiler: "gcc-latest"
    container:
      image: ghcr.io/seqan/${{ matrix.compiler }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Nextflow
        if: matrix.name == 'Nextflow'
        working-directory: /usr/local/bin
        run: |
          apt-get update
          apt-get install --yes default-jre-headless
          curl -s https://get.nextflow.io | bash

      - name: Install cwltool
        if: matrix.name == 'CWL'
        run: |
          apt-get update
          apt-get install --yes cwltool

      - name: Configure Raptor
        run: |
          mkdir build && cd build
          cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wno-interference-size"

      - name: Build Raptor
        working-directory: build
        run: |
          ccache -z
          make -k
          make install
          ccache -svvx

      - name: Run Nextflow
        if: matrix.name == 'Nextflow'
        working-directory: workflow/nextflow
        run: nextflow hibf.nf

      - name: Run cwltool
        if: matrix.name == 'CWL'
        run: |
          raptor build --export-help cwl > raptor.cwl
          cwltool --validate raptor.cwl
          cwltool raptor.cwl workflow/cwl/tests/raptor-build-0_bins_window_19.yml
          cwltool raptor.cwl workflow/cwl/tests/raptor-build-16_bins_window_19.yml

